### ISSUE TITLE
Performance in Wiki Pages

### ISSUE THREAD

**Issue by chkitzler** [alphanodes/additionals#167] opened 2023-06-30 08:28 UTC
we upgraded our Remine Instance to 5.0.5 running in docker
additionals plugin is running in latest version.

Wiki Pages with some references to Issues or Users (~48 @user, ~52 #issues) are very slow. Without additionals plugin: 600 ms , with additionals plugin 6100ms

we moved all other plugins so additional is the only plugin in this installation. 

Anyone help?

Regards Christoph

**Comment by alexandermeindl** [comment] 2023-10-19 10:22
Hi @chkitzler,
I cannot reproduce this behavior. Do you use any performance consuming macro for your sidebar settings? What do you mean with "some references to Issues or Users"? Can you give me for details about this? Which text formating do you use?

**Comment by alexandermeindl** [comment] 2024-03-10 10:17
Because of no further feedback, I close this issue.

**Closed by alexandermeindl** 2024-03-10 10:17 UTC
Labels: not confirmed
